language: php

php:
    - 7.1
    - 7.0
    - 5.6

cache:
    directories:
        - ~/.composer/cache/files

install:
    - composer update --prefer-dist

script:
    - composer validate --strict --no-check-all
    - vendor/bin/phpunit --coverage-clover coverage.clover --stderr --verbose

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
